Repository IgniteUI/igniteui-blazor-examples, pull requests merged in 2023-04, with the labels that each got.

#343 Dialog - Add samples
  samples/notifications/dialog/closing-variations/App.razor
  samples/notifications/dialog/closing-variations/BlazorClientApp.csproj
  samples/notifications/dialog/closing-variations/BlazorClientApp.sln
  samples/notifications/dialog/closing-variations/Program.cs
  samples/notifications/dialog/closing-variations/Properties/launchSettings.json
  samples/notifications/dialog/closing-variations/README.md
  samples/notifications/dialog/closing-variations/_Imports.razor
  samples/notifications/dialog/closing-variations/wwwroot/index.css
  samples/notifications/dialog/closing-variations/wwwroot/index.html
  samples/notifications/dialog/form/App.razor
  samples/notifications/dialog/form/BlazorClientApp.csproj
  samples/notifications/dialog/form/BlazorClientApp.sln
  samples/notifications/dialog/form/Program.cs
  samples/notifications/dialog/form/Properties/launchSettings.json
  samples/notifications/dialog/form/README.md
  samples/notifications/dialog/form/README.md.bak
  samples/notifications/dialog/form/_Imports.razor
  samples/notifications/dialog/form/wwwroot/index.css
  samples/notifications/dialog/form/wwwroot/index.html
  samples/notifications/dialog/overview/App.razor
  samples/notifications/dialog/overview/BlazorClientApp.csproj
  samples/notifications/dialog/overview/BlazorClientApp.sln
  samples/notifications/dialog/overview/Program.cs
  samples/notifications/dialog/overview/Properties/launchSettings.json
  samples/notifications/dialog/overview/README.md
  samples/notifications/dialog/overview/_Imports.razor
  samples/notifications/dialog/overview/wwwroot/index.css
  samples/notifications/dialog/overview/wwwroot/index.html
  samples/notifications/dialog/styling/App.razor
  samples/notifications/dialog/styling/BlazorClientApp.csproj
  samples/notifications/dialog/styling/BlazorClientApp.sln
  samples/notifications/dialog/styling/Program.cs
  samples/notifications/dialog/styling/Properties/launchSettings.json
  samples/notifications/dialog/styling/README.md
  samples/notifications/dialog/styling/README.md.bak
  samples/notifications/dialog/styling/_Imports.razor
  samples/notifications/dialog/styling/wwwroot/index.css
  samples/notifications/dialog/styling/wwwroot/index.html
Labels: status: verified

#353 mdd-add-excel-style-filtering-samples
  browser/IgBlazorSamples.Client/wwwroot/index.html
  browser/IgBlazorSamples.Gulp/tasks/gulp-samples.js
Labels: status: in-review

#354 mdd-updates
  samples/grids/grid/data-searching/App.razor
  samples/grids/grid/row-selection-mode/App.razor
Labels: status: in-review

#363 Add cell selection styling sample.
  browser/IgBlazorSamples.Gulp/tasks/gulp-samples.js
  samples/grids/grid/cell-selection-style/App.razor
  samples/grids/grid/cell-selection-style/BlazorClientApp.csproj
  samples/grids/grid/cell-selection-style/BlazorClientApp.sln
  samples/grids/grid/cell-selection-style/NwindData.cs
  samples/grids/grid/cell-selection-style/Program.cs
  samples/grids/grid/cell-selection-style/Properties/launchSettings.json
  samples/grids/grid/cell-selection-style/ReadMe.md
  samples/grids/grid/cell-selection-style/_Imports.razor
  samples/grids/grid/cell-selection-style/wwwroot/index.css
  samples/grids/grid/cell-selection-style/wwwroot/index.html
Labels: status: in-review

#362 Add groupby styling sample.
  browser/IgBlazorSamples.Gulp/tasks/gulp-samples.js
  samples/grids/grid/groupby-styling/App.razor
  samples/grids/grid/groupby-styling/BlazorClientApp.csproj
  samples/grids/grid/groupby-styling/BlazorClientApp.sln
  samples/grids/grid/groupby-styling/InvoicesData.cs
  samples/grids/grid/groupby-styling/Program.cs
  samples/grids/grid/groupby-styling/Properties/launchSettings.json
  samples/grids/grid/groupby-styling/ReadMe.md
  samples/grids/grid/groupby-styling/_Imports.razor
  samples/grids/grid/groupby-styling/wwwroot/index.css
  samples/grids/grid/groupby-styling/wwwroot/index.html
Labels: status: in-review, status: in-test
