Repository IgniteUI/igniteui-blazor-examples, pull requests merged in 2023-12, with the labels that each got.

#561 mdd-add-custom-tool
  samples/charts/toolbar/custom-tool/App.razor
  samples/charts/toolbar/custom-tool/BlazorClientApp.csproj
  samples/charts/toolbar/custom-tool/BlazorClientApp.sln
  samples/charts/toolbar/custom-tool/CountryRenewableElectricity.cs
  samples/charts/toolbar/custom-tool/Program.cs
  samples/charts/toolbar/custom-tool/Properties/launchSettings.json
  samples/charts/toolbar/custom-tool/ReadMe.md
  samples/charts/toolbar/custom-tool/_Imports.razor
  samples/charts/toolbar/custom-tool/wwwroot/index.css
  samples/charts/toolbar/custom-tool/wwwroot/index.html
Labels: status: in-review

#367 Update clipboard operations sample.
  samples/grids/grid/clipboard-operations/App.razor
  samples/grids/grid/clipboard-operations/Program.cs
  samples/grids/grid/clipboard-operations/wwwroot/events.js
Labels: status: in-test

#375 Make small changes in MCH template sample
  browser/IgBlazorSamples.Gulp/tasks/gulp-samples.js
  samples/grids/grid/multi-column-header-template/App.razor
  samples/grids/grid/multi-column-header-template/BlazorClientApp.csproj
  samples/grids/grid/multi-column-header-template/BlazorClientApp.sln
  samples/grids/grid/multi-column-header-template/CustomersData.cs
  samples/grids/grid/multi-column-header-template/Program.cs
  samples/grids/grid/multi-column-header-template/Properties/launchSettings.json
  samples/grids/grid/multi-column-header-template/ReadMe.md
  samples/grids/grid/multi-column-header-template/_Imports.razor
  samples/grids/grid/multi-column-header-template/wwwroot/MultiColumnHeaderTemplateEvents.js
  samples/grids/grid/multi-column-header-template/wwwroot/index.css
  samples/grids/grid/multi-column-header-template/wwwroot/index.html
Labels: status: do-not-merge

#438 Infinite scroll sample
  samples/grids/grid/infinite-scroll/App.razor
  samples/grids/grid/infinite-scroll/BlazorClientApp.csproj
  samples/grids/grid/infinite-scroll/BlazorClientApp.sln
  samples/grids/grid/infinite-scroll/NwindDataModel.cs
  samples/grids/grid/infinite-scroll/Program.cs
  samples/grids/grid/infinite-scroll/Properties/launchSettings.json
  samples/grids/grid/infinite-scroll/ReadMe.md
  samples/grids/grid/infinite-scroll/_Imports.razor
  samples/grids/grid/infinite-scroll/wwwroot/index.css
  samples/grids/grid/infinite-scroll/wwwroot/index.html
Labels: status: in-review
