Repository IgniteUI/igniteui-blazor-examples, pull requests merged in 2024-09, with the labels that each got.

#783 Add change icons in grid blazor sample.
  samples/grids/grid/change-icons-custom/App.razor
  samples/grids/grid/change-icons-custom/BlazorClientApp.csproj
  samples/grids/grid/change-icons-custom/BlazorClientApp.sln
  samples/grids/grid/change-icons-custom/NwindData.cs
  samples/grids/grid/change-icons-custom/Program.cs
  samples/grids/grid/change-icons-custom/Properties/launchSettings.json
  samples/grids/grid/change-icons-custom/ReadMe.md
  samples/grids/grid/change-icons-custom/_Imports.razor
  samples/grids/grid/change-icons-custom/wwwroot/index.css
  samples/grids/grid/change-icons-custom/wwwroot/index.html
Labels: status: in-review

#789 Add Banner samples
  samples/notifications/banner/banner-advanced-sample/App.razor
  samples/notifications/banner/banner-advanced-sample/BlazorClientApp.csproj
  samples/notifications/banner/banner-advanced-sample/BlazorClientApp.sln
  samples/notifications/banner/banner-advanced-sample/Program.cs
  samples/notifications/banner/banner-advanced-sample/Properties/launchSettings.json
  samples/notifications/banner/banner-advanced-sample/README.md
  samples/notifications/banner/banner-advanced-sample/_Imports.razor
  samples/notifications/banner/banner-advanced-sample/wwwroot/index.css
  samples/notifications/banner/banner-advanced-sample/wwwroot/index.html
  samples/notifications/banner/banner-sample-1/App.razor
  samples/notifications/banner/banner-sample-1/BlazorClientApp.csproj
  samples/notifications/banner/banner-sample-1/BlazorClientApp.sln
  samples/notifications/banner/banner-sample-1/Program.cs
  samples/notifications/banner/banner-sample-1/Properties/launchSettings.json
  samples/notifications/banner/banner-sample-1/README.md
  samples/notifications/banner/banner-sample-1/_Imports.razor
  samples/notifications/banner/banner-sample-1/wwwroot/index.css
  samples/notifications/banner/banner-sample-1/wwwroot/index.html
  samples/notifications/banner/banner-sample-2/App.razor
  samples/notifications/banner/banner-sample-2/BlazorClientApp.csproj
  samples/notifications/banner/banner-sample-2/BlazorClientApp.sln
  samples/notifications/banner/banner-sample-2/Program.cs
  samples/notifications/banner/banner-sample-2/Properties/launchSettings.json
  samples/notifications/banner/banner-sample-2/README.md
  samples/notifications/banner/banner-sample-2/_Imports.razor
  samples/notifications/banner/banner-sample-2/wwwroot/index.css
  samples/notifications/banner/banner-sample-2/wwwroot/index.html
  samples/notifications/banner/banner-styling/App.razor
  samples/notifications/banner/banner-styling/BlazorClientApp.csproj
  samples/notifications/banner/banner-styling/BlazorClientApp.sln
  samples/notifications/banner/banner-styling/Program.cs
  samples/notifications/banner/banner-styling/Properties/launchSettings.json
  samples/notifications/banner/banner-styling/README.md
  samples/notifications/banner/banner-styling/_Imports.razor
  samples/notifications/banner/banner-styling/wwwroot/index.css
  samples/notifications/banner/banner-styling/wwwroot/index.html
Labels: status: verified

#770 docs(grid): excel style editing sample initial
  samples/grids/grid/editing-excel-style-custom/App.razor
  samples/grids/grid/editing-excel-style-custom/BlazorClientApp.csproj
  samples/grids/grid/editing-excel-style-custom/BlazorClientApp.sln
  samples/grids/grid/editing-excel-style-custom/NwindData.cs
  samples/grids/grid/editing-excel-style-custom/Program.cs
  samples/grids/grid/editing-excel-style-custom/Properties/launchSettings.json
  samples/grids/grid/editing-excel-style-custom/ReadMe.md
  samples/grids/grid/editing-excel-style-custom/_Imports.razor
  samples/grids/grid/editing-excel-style-custom/wwwroot/events.js
  samples/grids/grid/editing-excel-style-custom/wwwroot/index.css
  samples/grids/grid/editing-excel-style-custom/wwwroot/index.html
Labels: status: verified

#813 Enable date dimension for custom sample.
  samples/grids/pivot-grid/data-selector/App.razor
Labels: status: verified

#817 Adding Divider Samples
  samples/layouts/divider/base/App.razor
  samples/layouts/divider/base/BlazorClientApp.csproj
  samples/layouts/divider/base/BlazorClientApp.sln
  samples/layouts/divider/base/Program.cs
  samples/layouts/divider/base/Properties/launchSettings.json
  samples/layouts/divider/base/README.md
  samples/layouts/divider/base/_Imports.razor
  samples/layouts/divider/base/wwwroot/index.css
  samples/layouts/divider/base/wwwroot/index.html
  samples/layouts/divider/dashed/App.razor
  samples/layouts/divider/dashed/BlazorClientApp.csproj
  samples/layouts/divider/dashed/BlazorClientApp.sln
  samples/layouts/divider/dashed/Program.cs
  samples/layouts/divider/dashed/Properties/launchSettings.json
  samples/layouts/divider/dashed/README.md
  samples/layouts/divider/dashed/_Imports.razor
  samples/layouts/divider/dashed/wwwroot/index.css
  samples/layouts/divider/dashed/wwwroot/index.html
  samples/layouts/divider/middle/App.razor
  samples/layouts/divider/middle/BlazorClientApp.csproj
  samples/layouts/divider/middle/BlazorClientApp.sln
  samples/layouts/divider/middle/Program.cs
  samples/layouts/divider/middle/Properties/launchSettings.json
  samples/layouts/divider/middle/README.md
  samples/layouts/divider/middle/_Imports.razor
  samples/layouts/divider/middle/wwwroot/index.css
  samples/layouts/divider/middle/wwwroot/index.html
  samples/layouts/divider/select/App.razor
  samples/layouts/divider/select/BlazorClientApp.csproj
  samples/layouts/divider/select/BlazorClientApp.sln
  samples/layouts/divider/select/Program.cs
  samples/layouts/divider/select/Properties/launchSettings.json
  samples/layouts/divider/select/README.md
  samples/layouts/divider/select/_Imports.razor
  samples/layouts/divider/select/wwwroot/index.css
  samples/layouts/divider/select/wwwroot/index.html
  samples/layouts/divider/vertical/App.razor
  samples/layouts/divider/vertical/BlazorClientApp.csproj
  samples/layouts/divider/vertical/BlazorClientApp.sln
  samples/layouts/divider/vertical/Program.cs
  samples/layouts/divider/vertical/Properties/launchSettings.json
  samples/layouts/divider/vertical/README.md
  samples/layouts/divider/vertical/_Imports.razor
  samples/layouts/divider/vertical/wwwroot/index.css
  samples/layouts/divider/vertical/wwwroot/index.html
Labels: status: verified, status: in-test

#778 mdd-33040
  samples/gauges/radial-gauge/labels/App.razor
Labels: status: in-review

#769 docs(grids): custom samples remote paging
  browser/IgBlazorSamples.Client/Program.cs
  samples/grids/grid/remote-paging-data/App.razor
  samples/grids/grid/remote-paging-data/NwindData.cs
  samples/grids/grid/remote-paging-grid/App.razor
  samples/grids/grid/remote-paging-grid/BlazorClientApp.csproj
  samples/grids/grid/remote-paging-grid/BlazorClientApp.sln
  samples/grids/grid/remote-paging-grid/FlatGridData.cs
  samples/grids/grid/remote-paging-grid/Program.cs
  samples/grids/grid/remote-paging-grid/Properties/launchSettings.json
  samples/grids/grid/remote-paging-grid/ReadMe.md
  samples/grids/grid/remote-paging-grid/_Imports.razor
  samples/grids/grid/remote-paging-grid/wwwroot/index.css
  samples/grids/grid/remote-paging-grid/wwwroot/index.html
  samples/grids/hierarchical-grid/remote-paging-hgrid/App.razor
  samples/grids/hierarchical-grid/remote-paging-hgrid/BlazorClientApp.csproj
  samples/grids/hierarchical-grid/remote-paging-hgrid/BlazorClientApp.sln
  samples/grids/hierarchical-grid/remote-paging-hgrid/HGridData.cs
  samples/grids/hierarchical-grid/remote-paging-hgrid/Program.cs
  samples/grids/hierarchical-grid/remote-paging-hgrid/Properties/launchSettings.json
  samples/grids/hierarchical-grid/remote-paging-hgrid/ReadMe.md
  samples/grids/hierarchical-grid/remote-paging-hgrid/_Imports.razor
  samples/grids/hierarchical-grid/remote-paging-hgrid/wwwroot/index.css
  samples/grids/hierarchical-grid/remote-paging-hgrid/wwwroot/index.html
Labels: status: verified
