Repository IgniteUI/igniteui-blazor-examples, pull requests merged in 2025-01, with the labels that each got.

#920 mdd-add-custom-content-grid-toolbar
  samples/grids/grid/toolbar-sample-4/App.razor
  samples/grids/grid/toolbar-sample-4/Program.cs
  samples/grids/grid/toolbar-sample-4/wwwroot/events.js
  samples/grids/grid/toolbar-sample-4/wwwroot/index.html
Labels: status: in-review

#823 Add generic sample tests and test generation.
  .gitignore
  azure-pipelines/NuGet.config
  azure-pipelines/templates/build-steps-template.yml
  browser/.runsettings
  browser/IgBlazorSamples.Gulp/gulpfile.js
  browser/IgBlazorSamples.Gulp/tasks/gulp-samples.js
  browser/IgBlazorSamples.Test.sln
  browser/IgBlazorSamples.Test/BasicTests.cs
  browser/IgBlazorSamples.Test/IgBlazorSamples.Test.csproj
  browser/IgBlazorSamples.Test/Infrastructure/BlazorTest.cs
  browser/IgBlazorSamples.Test/Models/SettingsModel.cs
  browser/IgBlazorSamples.Test/ReadMe.md
  browser/IgBlazorSamples.Test/SampleErrorTests.cs
  browser/IgBlazorSamples.Test/TestUtils.cs
  browser/IgBlazorSamples.Test/testsettings.json
  browser/IgBlazorSamples.TestServer/IgBlazorSamples.TestServer.csproj
  browser/IgBlazorSamples.TestServer/Pages/Error.cshtml
  browser/IgBlazorSamples.TestServer/Pages/Error.cshtml.cs
  browser/IgBlazorSamples.TestServer/Program.cs
  browser/IgBlazorSamples.TestServer/Properties/AssemblyInfo.cs
  browser/IgBlazorSamples.TestServer/Properties/launchSettings.json
  browser/IgBlazorSamples.TestServer/ReadMe.md
  browser/IgBlazorSamples.TestServer/appsettings.Development.json
  browser/IgBlazorSamples.TestServer/appsettings.json
Labels: squash-merge

#842 Change how grids save state on navigation
  samples/grids/grid/state-persistence-main/App.razor
  samples/grids/hierarchical-grid/state-persistence-main/App.razor
  samples/grids/pivot-grid/state-persistence-main/App.razor
  samples/grids/tree-grid/state-persistence-main/App.razor
Labels: status: verified
